In [1]:
import torch
import numpy as np

from src.tensor import Tensor

In [2]:
lists: list[list[float]] = [
    [
        [1.0, 2.0, 3.0, 4.0, 5.0],
        [-1.0, 2.0, -3.0, 4.0, -5.0]
    ],
    [
        [-0.1, 0.2, -0.3, 0.4, -0.5],
        [-0.01, 4, -3.7, 8.1, -13.5]
    ]
]
arr: np.ndarray[np.float32] = np.array(lists).astype(np.float32)

x = Tensor(arr)
x_torch: torch.Tensor = torch.tensor(arr, requires_grad=True)

_max: Tensor = x.max()
_max_torch: torch.Tensor = x_torch.max()

shifted_value = x - _max
shifted_value_torch = x_torch - _max_torch

exp_value = shifted_value.exp()
exp_value_torch = shifted_value_torch.exp()

row_reduce = exp_value.sum(axis=-1, keepdim=True)
row_reduce_torch = exp_value_torch.sum(axis=-1, keepdim=True)

z = row_reduce.sum()
z_torch = row_reduce_torch.sum()

z.backward()
z_torch.backward()

In [3]:
x_vals: np.ndarray[np.float32] = np.array([[1, 2, 3], [4, 5, 6]]).astype(np.float32)

x = Tensor(x_vals)
x_torch = torch.tensor(x_vals, requires_grad=True)

y = x.sum(axis = -1, keepdim=True)
y_torch = x_torch.sum(axis = -1, keepdim=True)

z = y.sum()
z_torch = y_torch.sum()

z.backward()
z_torch.backward()

x_torch.grad, x.grad

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32))

In [4]:
y, y_torch

(Tensor([[ 6.],
         [15.]]),
 tensor([[ 6.],
         [15.]], grad_fn=<SumBackward1>))